preload = /home/pindjouf/.config/assets/19.jpg

# wallpaper {
#     monitor = DP-1
#     path = ~/.config/Wallpapers/wallpaper.png
#     fit_mode = cover
# }

wallpaper {
    monitor = HDMI-A-1
    path = /home/pindjouf/.config/assets/19.jpg
    fit_mode = cover
}

splash = false
ipc = off
